# Generated by Django 5.0.1 on 2024-01-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_employeeinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='numder',
            new_name='number',
        ),
    ]
